version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  upfit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upfit-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}


volumes:
  mysql-data: